### ISSUE TITLE
Nation Delete Removing Town Perms

### ISSUE THREAD

**Issue by TylorTurner** [Wyzebb/TownyDiscordBridge#1]
**Describe the bug**
When Nations are deleted the Town permission gets removed.
The town is still active and they should retain the town permissions

**How To Reproduce**
Steps to reproduce the bug:
/t create town
/t create nation
/t delete nation
^ Removed all town permissions

**Comment by Wyzebb** [comment]
**Bug fixed**
New behaviour: when a nation is deleted, the player should keep their town roles.


There is a good chance there are still cases where players will have their permissions incorrectly removed since there are a lot of ways the original code for removing the town and nation permissions, rather than just one of these, can be called.

Please reopen this issue and state how the issue can be reproduced if this happens!

**Comment by Wyzebb** [comment]
✅ When a town removes itself from a nation, the town roles should be kept, but the nation role should be removed
❌ When you leave a town, both the nation and town roles should be removed

**Comment by Wyzebb** [comment]
Should be fixed as of dev build 3, pending review from @TylorTurner

**Comment by TylorTurner** [comment]
Still not fixed, /N leavenation 
"/ta town NAME leavenation"
still leaves old nation perms on player.

A nation requires a player to be in a town. If a town leave a nation they should still retain their town perm.

**Comment by Wyzebb** [comment]
I believe everything is working now as of build [TDB-1.0.0+DEV7](https://github.com/Wyzebb/TownyDiscordBridge/releases/tag/v1.0.0-DEV7):
✅ Nation roles will be removed correctly when nations are deleted
✅ Nation roles will be removed if a player leaves or gets kicked from a town

Awaiting approval from @TylorTurner

**Comment by Wyzebb** [comment]
Verified working as intended by Tylor ✅
